In [ ]:
#ataset Link = https://github.com/DataScience75/Top_mentor_projects_Datasets/blob/main/customer_reviews.csv
#Groq URL = https://console.groq.com/playground

In [ ]:
!pip install faiss-cpu groq python-dotenv

Collecting faiss-cpu
  Downloading faiss_cpu-1.14.2-cp310-abi3-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (7.8 kB)
Collecting groq
  Downloading groq-1.4.0-py3-none-any.whl.metadata (16 kB)
Requirement already satisfied: python-dotenv in /usr/local/lib/python3.12/dist-packages (1.2.2)
Requirement already satisfied: numpy>=1.25 in /usr/local/lib/python3.12/dist-packages (from faiss-cpu) (2.0.2)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from faiss-cpu) (26.2)
Requirement already satisfied: anyio<5,>=3.5.0 in /usr/local/lib/python3.12/dist-packages (from groq) (4.13.0)
Requirement already satisfied: distro<2,>=1.7.0 in /usr/local/lib/python3.12/dist-packages (from groq) (1.9.0)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from groq) (0.28.1)
Requirement already satisfied: pydantic<3,>=1.9.0 in /usr/local/lib/python3.12/dist-packages (from groq) (2.12.3)
Requirement already satisfied: sniffio in /usr/local/lib/python3.12/dist-packages (from groq) (1.3.1)
Requirement already satisfied: typing-extensions<5,>=4.14 in /usr/local/lib/python3.12/dist-packages (from groq) (4.15.0)
Requirement already satisfied: idna>=2.8 in /usr/local/lib/python3.12/dist-packages (from anyio<5,>=3.5.0->groq) (3.18)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->groq) (2026.5.20)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->groq) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->groq) (0.16.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=1.9.0->groq) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=1.9.0->groq) (2.41.4)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=1.9.0->groq) (0.4.2)
Downloading faiss_cpu-1.14.2-cp310-abi3-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (18.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.2/18.2 MB 35.4 MB/s eta 0:00:00
Downloading groq-1.4.0-py3-none-any.whl (143 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 143.7/143.7 kB 6.7 MB/s eta 0:00:00
Installing collected packages: faiss-cpu, groq
Successfully installed faiss-cpu-1.14.2 groq-1.4.0

In [ ]:
import pandas as pd
import numpy as np
import faiss
from sentence_transformers import SentenceTransformer
from groq import Groq
from sklearn.metrics import precision_score
from dotenv import load_dotenv
import os
import re

In [ ]:
groq_api_key = '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'
client = Groq(api_key=groq_api_key)

In [ ]:
df = pd.read_csv('/content/iphone.csv')
df.head(5)

,productAsin,country,date,isVerified,ratingScore,reviewTitle,reviewDescription,reviewUrl,reviewedIn,variant,variantAsin
0,B09G9BL5CP,India,11-08-2024,True,4,No charger,"Every thing is good about iPhones, there's not...",https://www.amazon.in/gp/customer-reviews/R345...,Reviewed in India on 11 August 2024,Colour: MidnightSize: 256 GB,B09G9BQS98
1,B09G9BL5CP,India,16-08-2024,True,5,iPhone 13 256GB,"It look so fabulous, I am android user switche...",https://www.amazon.in/gp/customer-reviews/R2HJ...,Reviewed in India on 16 August 2024,Colour: MidnightSize: 256 GB,B09G9BQS98
2,B09G9BL5CP,India,14-05-2024,True,4,Flip camera option nill,I tried to flip camera while recording but no ...,https://www.amazon.in/gp/customer-reviews/R3Y7...,Reviewed in India on 14 May 2024,Colour: MidnightSize: 256 GB,B09G9BQS98
3,B09G9BL5CP,India,24-06-2024,True,5,Product,100% genuine,https://www.amazon.in/gp/customer-reviews/R1P9...,Reviewed in India on 24 June 2024,Colour: MidnightSize: 256 GB,B09G9BQS98
4,B09G9BL5CP,India,18-05-2024,True,5,Good product,Happy to get the iPhone 13 in Amazon offer,https://www.amazon.in/gp/customer-reviews/R1XI...,Reviewed in India on 18 May 2024,Colour: MidnightSize: 256 GB,B09G9BQS98

In [ ]:
def preprocess_text(text):
  text = re.sub(r"\s+"," ",text)
  text = re.sub(r"[^a-zA-Z0-9 ]","",text)
  return text.strip().lower()

In [ ]:
df['reviewDescription'].astype("str").apply(preprocess_text)

0       every thing is good about iphones theres nothi...
1       it look so fabulous i am android user switched...
2       i tried to flip camera while recording but no ...
3                                             100 genuine
4              happy to get the iphone 13 in amazon offer
                              ...
3057    useless phon never buy this heat n useless cam...
3058    iam not happy with this product why because ch...
3059                                           good phone
3060    while charging mobile its getting so hot even ...
3061    battery power is be very bad need to chat on d...
Name: reviewDescription, Length: 3062, dtype: object

In [ ]:
df['clean_text'] = df['reviewDescription'].astype("str").apply(preprocess_text)
df

,productAsin,country,date,isVerified,ratingScore,reviewTitle,reviewDescription,reviewUrl,reviewedIn,variant,variantAsin,clean_text
0,B09G9BL5CP,India,11-08-2024,True,4,No charger,"Every thing is good about iPhones, there's not...",https://www.amazon.in/gp/customer-reviews/R345...,Reviewed in India on 11 August 2024,Colour: MidnightSize: 256 GB,B09G9BQS98,every thing is good about iphones theres nothi...
1,B09G9BL5CP,India,16-08-2024,True,5,iPhone 13 256GB,"It look so fabulous, I am android user switche...",https://www.amazon.in/gp/customer-reviews/R2HJ...,Reviewed in India on 16 August 2024,Colour: MidnightSize: 256 GB,B09G9BQS98,it look so fabulous i am android user switched...
2,B09G9BL5CP,India,14-05-2024,True,4,Flip camera option nill,I tried to flip camera while recording but no ...,https://www.amazon.in/gp/customer-reviews/R3Y7...,Reviewed in India on 14 May 2024,Colour: MidnightSize: 256 GB,B09G9BQS98,i tried to flip camera while recording but no ...
3,B09G9BL5CP,India,24-06-2024,True,5,Product,100% genuine,https://www.amazon.in/gp/customer-reviews/R1P9...,Reviewed in India on 24 June 2024,Colour: MidnightSize: 256 GB,B09G9BQS98,100 genuine
4,B09G9BL5CP,India,18-05-2024,True,5,Good product,Happy to get the iPhone 13 in Amazon offer,https://www.amazon.in/gp/customer-reviews/R1XI...,Reviewed in India on 18 May 2024,Colour: MidnightSize: 256 GB,B09G9BQS98,happy to get the iphone 13 in amazon offer
...,...,...,...,...,...,...,...,...,...,...,...,...
3057,B09G9D8KRQ,India,11-10-2023,True,1,Very bad experience with i phone 13,Useless phon never buy this heat n useless cam...,https://www.amazon.in/gp/customer-reviews/R10O...,Reviewed in India on 11 October 2023,Colour: (PRODUCT) REDSize: 128 GB,B09G99CW2N,useless phon never buy this heat n useless cam...
3058,B09G9D8KRQ,India,14-10-2022,True,2,not happy with this apple product,iam not happy with this product why because ch...,https://www.amazon.in/gp/customer-reviews/R2FW...,Reviewed in India on 14 October 2022,Colour: (PRODUCT) REDSize: 128 GB,B09G99CW2N,iam not happy with this product why because ch...
3059,B09G9D8KRQ,India,24-02-2022,True,3,Good phone,Good phone,https://www.amazon.in/gp/customer-reviews/R2C7...,Reviewed in India on 24 February 2022,Colour: (PRODUCT) REDSize: 128 GB,B09G99CW2N,good phone
3060,B09G9D8KRQ,India,16-10-2023,True,1,Battery discharge,While charging mobile it's getting so hot even...,https://www.amazon.in/gp/customer-reviews/R3K0...,Reviewed in India on 16 October 2023,Colour: (PRODUCT) REDSize: 128 GB,B09G99CW2N,while charging mobile its getting so hot even ...
3061,B09G9D8KRQ,India,11-11-2023,True,1,Batter power needs to be improved,Battery power is be very bad need to chat on d...,https://www.amazon.in/gp/customer-reviews/R2QO...,Reviewed in India on 11 November 2023,Colour: (PRODUCT) REDSize: 128 GB,B09G99CW2N,battery power is be very bad need to chat on d...

In [ ]:
def chunk_text(text,chunk_size=20):
  words = text.split()
  return[" ".join(words[i:i+chunk_size]) for i in range(0,len(words),chunk_size)]

In [ ]:
chunks = []
metadata = []
for idx, row in df.iterrows():
  for clean_chunk in chunk_text(row['clean_text']):
    chunks.append(clean_chunk)
    metadata.append({'product_id':row['productAsin'],'review_id':idx})

In [ ]:
metadata

[{'product_id': 'B09G9BL5CP', 'review_id': 0},
 {'product_id': 'B09G9BL5CP', 'review_id': 0},
 {'product_id': 'B09G9BL5CP', 'review_id': 0},
 {'product_id': 'B09G9BL5CP', 'review_id': 0},
 {'product_id': 'B09G9BL5CP', 'review_id': 1},
 {'product_id': 'B09G9BL5CP', 'review_id': 1},
 {'product_id': 'B09G9BL5CP', 'review_id': 2},
 {'product_id': 'B09G9BL5CP', 'review_id': 2},
 {'product_id': 'B09G9BL5CP', 'review_id': 2},
 {'product_id': 'B09G9BL5CP', 'review_id': 2},
 {'product_id': 'B09G9BL5CP', 'review_id': 2},
 {'product_id': 'B09G9BL5CP', 'review_id': 3},
 {'product_id': 'B09G9BL5CP', 'review_id': 4},
 {'product_id': 'B09G9BL5CP', 'review_id': 5},
 {'product_id': 'B09G9BL5CP', 'review_id': 6},
 {'product_id': 'B09G9BL5CP', 'review_id': 6},
 {'product_id': 'B09G9BL5CP', 'review_id': 7},
 {'product_id': 'B09G9BL5CP', 'review_id': 8},
 {'product_id': 'B09G9BL5CP', 'review_id': 9},
 {'product_id': 'B09G9BL5CP', 'review_id': 10},
 {'product_id': 'B09G9BL5CP', 'review_id': 10},
 {'product_id': 'B09G9BL5CP', 'review_id': 10},
 {'product_id': 'B09G9BL5CP', 'review_id': 10},
 {'product_id': 'B09G9BL5CP', 'review_id': 10},
 {'product_id': 'B09G9BL5CP', 'review_id': 10},
 {'product_id': 'B09G9BL5CP', 'review_id': 10},
 {'product_id': 'B09G9BL5CP', 'review_id': 10},
 {'product_id': 'B09G9BL5CP', 'review_id': 10},
 {'product_id': 'B09G9BL5CP', 'review_id': 10},
 {'product_id': 'B09G9BL5CP', 'review_id': 10},
 {'product_id': 'B09G9BL5CP', 'review_id': 10},
 {'product_id': 'B09G9BL5CP', 'review_id': 10},
 {'product_id': 'B09G9BL5CP', 'review_id': 10},
 {'product_id': 'B09G9BL5CP', 'review_id': 10},
 {'product_id': 'B09G9BL5CP', 'review_id': 10},
 {'product_id': 'B09G9BL5CP', 'review_id': 10},
 {'product_id': 'B09G9BL5CP', 'review_id': 10},
 {'product_id': 'B09G9BL5CP', 'review_id': 10},
 {'product_id': 'B09G9BL5CP', 'review_id': 10},
 {'product_id': 'B09G9BL5CP', 'review_id': 10},
 {'product_id': 'B09G9BL5CP', 'review_id': 10},
 {'product_id': 'B09G9BL5CP', 'review_id': 10},
 {'product_id': 'B09G9BL5CP', 'review_id': 10},
 {'product_id': 'B09G9BL5CP', 'review_id': 11},
 {'product_id': 'B09G9BL5CP', 'review_id': 12},
 {'product_id': 'B09G9BL5CP', 'review_id': 13},
 {'product_id': 'B09G9BL5CP', 'review_id': 13},
 {'product_id': 'B09G9BL5CP', 'review_id': 14},
 {'product_id': 'B09G9BL5CP', 'review_id': 15},
 {'product_id': 'B09G9BL5CP', 'review_id': 15},
 {'product_id': 'B09G9BL5CP', 'review_id': 15},
 {'product_id': 'B09G9BL5CP', 'review_id': 15},
 {'product_id': 'B09G9BL5CP', 'review_id': 15},
 {'product_id': 'B09G9BL5CP', 'review_id': 15},
 {'product_id': 'B09G9BL5CP', 'review_id': 15},
 {'product_id': 'B09G9BL5CP', 'review_id': 15},
 {'product_id': 'B09G9BL5CP', 'review_id': 16},
 {'product_id': 'B09G9BL5CP', 'review_id': 16},
 {'product_id': 'B09G9BL5CP', 'review_id': 16},
 {'product_id': 'B09G9BL5CP', 'review_id': 17},
 {'product_id': 'B09G9BL5CP', 'review_id': 18},
 {'product_id': 'B09G9BL5CP', 'review_id': 18},
 {'product_id': 'B09G9BL5CP', 'review_id': 18},
 {'product_id': 'B09G9BL5CP', 'review_id': 19},
 {'product_id': 'B09G9BL5CP', 'review_id': 19},
 {'product_id': 'B09G9BL5CP', 'review_id': 20},
 {'product_id': 'B09G9BL5CP', 'review_id': 21},
 {'product_id': 'B09G9BL5CP', 'review_id': 22},
 {'product_id': 'B09G9BL5CP', 'review_id': 23},
 {'product_id': 'B09G9BL5CP', 'review_id': 24},
 {'product_id': 'B09G9BL5CP', 'review_id': 24},
 {'product_id': 'B09G9BL5CP', 'review_id': 24},
 {'product_id': 'B09G9BL5CP', 'review_id': 24},
 {'product_id': 'B09G9BL5CP', 'review_id': 25},
 {'product_id': 'B09G9BL5CP', 'review_id': 26},
 {'product_id': 'B09G9BL5CP', 'review_id': 27},
 {'product_id': 'B09G9BL5CP', 'review_id': 28},
 {'product_id': 'B09G9BL5CP', 'review_id': 28},
 {'product_id': 'B09G9BL5CP', 'review_id': 28},
 {'product_id': 'B09G9BL5CP', 'review_id': 28},
 {'product_id': 'B09G9BL5CP', 'review_id': 29},
 {'product_id': 'B09G9BL5CP', 'review_id': 30},
 {'product_id': 'B09G9BL5CP', 'review_id': 31},
 {'product_id': 'B09G9BL5CP', 'review_id': 32},
 {'product_id': 'B09G9BL5CP', 'review_id': 33},
 {'product_id': 'B09G9BL5CP', 'review_id': 34},
 {'product_id': 'B09G9BL5CP', 'review_id': 35},
 {'product_id': 'B09G9BL5CP', 'review_id': 35},
 {'product_id': 'B09G9BL5CP', 'review_id': 35},
 {'product_id': 'B09G9BL5CP', 'review_id': 35},
 {'product_id': 'B09G9BL5CP', 'review_id': 36},
 {'product_id': 'B09G9BL5CP', 'review_id': 36},
 {'product_id': 'B09G9BL5CP', 'review_id': 36},
 {'product_id': 'B09G9BL5CP', 'review_id': 37},
 {'product_id': 'B09G9BL5CP', 'review_id': 38},
 {'product_id': 'B09G9BL5CP', 'review_id': 38},
 {'product_id': 'B09G9BL5CP', 'review_id': 39},
 {'product_id': 'B09G9BL5CP', 'review_id': 39},
 {'product_id': 'B09G9BL5CP', 'review_id': 40},
 {'product_id': 'B09G9BL5CP', 'review_id': 40},
 {'product_id': 'B09G9BL5CP', 'review_id': 40},
 {'product_id': 'B09G9BL5CP', 'review_id': 40},
 {'product_id': 'B09G9BL5CP', 'review_id': 40},
 {'product_id': 'B09G9BL5CP', 'review_id': 40},
 {'product_id': 'B09G9BL5CP', 'review_id': 40},
 {'product_id': 'B09G9BL5CP', 'review_id': 40},
 {'product_id': 'B09G9BL5CP', 'review_id': 40},
 {'product_id': 'B09G9BL5CP', 'review_id': 41},
 {'product_id': 'B09G9BL5CP', 'review_id': 41},
 {'product_id': 'B09G9BL5CP', 'review_id': 41},
 {'product_id': 'B09G9BL5CP', 'review_id': 42},
 {'product_id': 'B09G9BL5CP', 'review_id': 42},
 {'product_id': 'B09G9BL5CP', 'review_id': 42},
 {'product_id': 'B09G9BL5CP', 'review_id': 42},
 {'product_id': 'B09G9BL5CP', 'review_id': 42},
 {'product_id': 'B09G9BL5CP', 'review_id': 42},
 {'product_id': 'B09G9BL5CP', 'review_id': 42},
 {'product_id': 'B09G9BL5CP', 'review_id': 42},
 {'product_id': 'B09G9BL5CP', 'review_id': 42},
 {'product_id': 'B09G9BL5CP', 'review_id': 42},
 {'product_id': 'B09G9BL5CP', 'review_id': 42},
 {'product_id': 'B09G9BL5CP', 'review_id': 42},
 {'product_id': 'B09G9BL5CP', 'review_id': 43},
 {'product_id': 'B09G9BL5CP', 'review_id': 44},
 {'product_id': 'B09G9BL5CP', 'review_id': 45},
 {'product_id': 'B09G9BL5CP', 'review_id': 45},
 {'product_id': 'B09G9BL5CP', 'review_id': 45},
 {'product_id': 'B09G9BL5CP', 'review_id': 45},
 {'product_id': 'B09G9BL5CP', 'review_id': 45},
 {'product_id': 'B09G9BL5CP', 'review_id': 45},
 {'product_id': 'B09G9BL5CP', 'review_id': 45},
 {'product_id': 'B09G9BL5CP', 'review_id': 45},
 {'product_id': 'B09G9BL5CP', 'review_id': 45},
 {'product_id': 'B09G9BL5CP', 'review_id': 45},
 {'product_id': 'B09G9BL5CP', 'review_id': 45},
 {'product_id': 'B09G9BL5CP', 'review_id': 45},
 {'product_id': 'B09G9BL5CP', 'review_id': 45},
 {'product_id': 'B09G9BL5CP', 'review_id': 45},
 {'product_id': 'B09G9BL5CP', 'review_id': 45},
 {'product_id': 'B09G9BL5CP', 'review_id': 45},
 {'product_id': 'B09G9BL5CP', 'review_id': 45},
 {'product_id': 'B09G9BL5CP', 'review_id': 45},
 {'product_id': 'B09G9BL5CP', 'review_id': 45},
 {'product_id': 'B09G9BL5CP', 'review_id': 45},
 {'product_id': 'B09G9BL5CP', 'review_id': 45},
 {'product_id': 'B09G9BL5CP', 'review_id': 45},
 {'product_id': 'B09G9BL5CP', 'review_id': 45},
 {'product_id': 'B09G9BL5CP', 'review_id': 45},
 {'product_id': 'B09G9BL5CP', 'review_id': 45},
 {'product_id': 'B09G9BL5CP', 'review_id': 45},
 {'product_id': 'B09G9BL5CP', 'review_id': 46},
 {'product_id': 'B09G9BL5CP', 'review_id': 46},
 {'product_id': 'B09G9BL5CP', 'review_id': 47},
 {'product_id': 'B09G9BL5CP', 'review_id': 48},
 {'product_id': 'B09G9BL5CP', 'review_id': 48},
 {'product_id': 'B09G9BL5CP', 'review_id': 48},
 {'product_id': 'B09G9BL5CP', 'review_id': 48},
 {'product_id': 'B09G9BL5CP', 'review_id': 48},
 {'product_id': 'B09G9BL5CP', 'review_id': 48},
 {'product_id': 'B09G9BL5CP', 'review_id': 48},
 {'product_id': 'B09G9BL5CP', 'review_id': 48},
 {'product_id': 'B09G9BL5CP', 'review_id': 49},
 {'product_id': 'B09G9BL5CP', 'review_id': 50},
 {'product_id': 'B09G9BL5CP', 'review_id': 51},
 {'product_id': 'B09G9BL5CP', 'review_id': 51},
 {'product_id': 'B09G9BL5CP', 'review_id': 52},
 {'product_id': 'B09G9BL5CP', 'review_id': 52},
 {'product_id': 'B09G9BL5CP', 'review_id': 53},
 {'product_id': 'B09G9BL5CP', 'review_id': 53},
 {'product_id': 'B09G9BL5CP', 'review_id': 53},
 {'product_id': 'B09G9BL5CP', 'review_id': 53},
 {'product_id': 'B09G9BL5CP', 'review_id': 53},
 {'product_id': 'B09G9BL5CP', 'review_id': 53},
 {'product_id': 'B09G9BL5CP', 'review_id': 53},
 {'product_id': 'B09G9BL5CP', 'review_id': 53},
 {'product_id': 'B09G9BL5CP', 'review_id': 53},
 {'product_id': 'B09G9BL5CP', 'review_id': 53},
 {'product_id': 'B09G9BL5CP', 'review_id': 53},
 {'product_id': 'B09G9BL5CP', 'review_id': 53},
 {'product_id': 'B09G9BL5CP', 'review_id': 53},
 {'product_id': 'B09G9BL5CP', 'review_id': 53},
 {'product_id': 'B09G9BL5CP', 'review_id': 53},
 {'product_id': 'B09G9BL5CP', 'review_id': 53},
 {'product_id': 'B09G9BL5CP', 'review_id': 53},
 {'product_id': 'B09G9BL5CP', 'review_id': 53},
 {'product_id': 'B09G9BL5CP', 'review_id': 53},
 {'product_id': 'B09G9BL5CP', 'review_id': 53},
 {'product_id': 'B09G9BL5CP', 'review_id': 53},
 {'product_id': 'B09G9BL5CP', 'review_id': 54},
 {'product_id': 'B09G9BL5CP', 'review_id': 55},
 {'product_id': 'B09G9BL5CP', 'review_id': 56},
 {'product_id': 'B09G9BL5CP', 'review_id': 56},
 {'product_id': 'B09G9BL5CP', 'review_id': 56},
 {'product_id': 'B09G9BL5CP', 'review_id': 57},
 {'product_id': 'B09G9BL5CP', 'review_id': 58},
 {'product_id': 'B09G9BL5CP', 'review_id': 58},
 {'product_id': 'B09G9BL5CP', 'review_id': 58},
 {'product_id': 'B09G9BL5CP', 'review_id': 58},
 {'product_id': 'B09G9BL5CP', 'review_id': 58},
 {'product_id': 'B09G9BL5CP', 'review_id': 58},
 {'product_id': 'B09G9BL5CP', 'review_id': 58},
 {'product_id': 'B09G9BL5CP', 'review_id': 58},
 {'product_id': 'B09G9BL5CP', 'review_id': 58},
 {'product_id': 'B09G9BL5CP', 'review_id': 59},
 {'product_id': 'B09G9BL5CP', 'review_id': 60},
 {'product_id': 'B09G9BL5CP', 'review_id': 61},
 {'product_id': 'B09G9BL5CP', 'review_id': 61},
 {'product_id': 'B09G9BL5CP', 'review_id': 61},
 {'product_id': 'B09G9BL5CP', 'review_id': 62},
 {'product_id': 'B09G9BL5CP', 'review_id': 63},
 {'product_id': 'B09G9BL5CP', 'review_id': 64},
 {'product_id': 'B09G9BL5CP', 'review_id': 65},
 {'product_id': 'B09G9BL5CP', 'review_id': 66},
 {'product_id': 'B09G9BL5CP', 'review_id': 66},
 {'product_id': 'B09G9BL5CP', 'review_id': 67},
 {'product_id': 'B09G9BL5CP', 'review_id': 68},
 {'product_id': 'B09G9BL5CP', 'review_id': 68},
 {'product_id': 'B09G9BL5CP', 'review_id': 69},
 {'product_id': 'B09G9BL5CP', 'review_id': 70},
 {'product_id': 'B09G9BL5CP', 'review_id': 70},
 {'product_id': 'B09G9BL5CP', 'review_id': 70},
 {'product_id': 'B09G9BL5CP', 'review_id': 71},
 {'product_id': 'B09G9BL5CP', 'review_id': 72},
 {'product_id': 'B09G9BL5CP', 'review_id': 74},
 {'product_id': 'B09G9BL5CP', 'review_id': 75},
 {'product_id': 'B09G9BL5CP', 'review_id': 76},
 {'product_id': 'B09G9BL5CP', 'review_id': 77},
 {'product_id': 'B09G9BL5CP', 'review_id': 78},
 {'product_id': 'B09G9BL5CP', 'review_id': 78},
 {'product_id': 'B09G9BL5CP', 'review_id': 78},
 {'product_id': 'B09G9BL5CP', 'review_id': 78},
 {'product_id': 'B09G9BL5CP', 'review_id': 78},
 {'product_id': 'B09G9BL5CP', 'review_id': 78},
 {'product_id': 'B09G9BL5CP', 'review_id': 78},
 {'product_id': 'B09G9BL5CP', 'review_id': 78},
 {'product_id': 'B09G9BL5CP', 'review_id': 78},
 {'product_id': 'B09G9BL5CP', 'review_id': 78},
 {'product_id': 'B09G9BL5CP', 'review_id': 78},
 {'product_id': 'B09G9BL5CP', 'review_id': 78},
 {'product_id': 'B09G9BL5CP', 'review_id': 78},
 {'product_id': 'B09G9BL5CP', 'review_id': 78},
 {'product_id': 'B09G9BL5CP', 'review_id': 78},
 {'product_id': 'B09G9BL5CP', 'review_id': 78},
 {'product_id': 'B09G9BL5CP', 'review_id': 78},
 {'product_id': 'B09G9BL5CP', 'review_id': 78},
 {'product_id': 'B09G9BL5CP', 'review_id': 78},
 {'product_id': 'B09G9BL5CP', 'review_id': 78},
 {'product_id': 'B09G9BL5CP', 'review_id': 78},
 {'product_id': 'B09G9BL5CP', 'review_id': 78},
 {'product_id': 'B09G9BL5CP', 'review_id': 78},
 {'product_id': 'B09G9BL5CP', 'review_id': 79},
 {'product_id': 'B09G9BL5CP', 'review_id': 79},
 {'product_id': 'B09G9BL5CP', 'review_id': 80},
 {'product_id': 'B09G9BL5CP', 'review_id': 80},
 {'product_id': 'B09G9BL5CP', 'review_id': 80},
 {'product_id': 'B09G9BL5CP', 'review_id': 80},
 {'product_id': 'B09G9BL5CP', 'review_id': 80},
 {'product_id': 'B09G9BL5CP', 'review_id': 80},
 {'product_id': 'B09G9BL5CP', 'review_id': 80},
 {'product_id': 'B09G9BL5CP', 'review_id': 80},
 {'product_id': 'B09G9BL5CP', 'review_id': 80},
 {'product_id': 'B09G9BL5CP', 'review_id': 80},
 {'product_id': 'B09G9BL5CP', 'review_id': 80},
 {'product_id': 'B09G9BL5CP', 'review_id': 80},
 {'product_id': 'B09G9BL5CP', 'review_id': 80},
 {'product_id': 'B09G9BL5CP', 'review_id': 81},
 {'product_id': 'B09G9BL5CP', 'review_id': 81},
 {'product_id': 'B09G9BL5CP', 'review_id': 81},
 {'product_id': 'B09G9BL5CP', 'review_id': 81},
 {'product_id': 'B09G9BL5CP', 'review_id': 81},
 {'product_id': 'B09G9BL5CP', 'review_id': 81},
 {'product_id': 'B09G9BL5CP', 'review_id': 81},
 {'product_id': 'B09G9BL5CP', 'review_id': 81},
 {'product_id': 'B09G9BL5CP', 'review_id': 82},
 {'product_id': 'B09G9BL5CP', 'review_id': 82},
 {'product_id': 'B09G9BL5CP', 'review_id': 83},
 {'product_id': 'B09G9BL5CP', 'review_id': 85},
 {'product_id': 'B09G9BL5CP', 'review_id': 86},
 {'product_id': 'B09G9BL5CP', 'review_id': 87},
 {'product_id': 'B09G9BL5CP', 'review_id': 88},
 {'product_id': 'B09G9BL5CP', 'review_id': 89},
 {'product_id': 'B09G9BL5CP', 'review_id': 89},
 {'product_id': 'B09G9BL5CP', 'review_id': 90},
 {'product_id': 'B09G9BL5CP', 'review_id': 91},
 {'product_id': 'B09G9BL5CP', 'review_id': 92},
 {'product_id': 'B09G9BL5CP', 'review_id': 93},
 {'product_id': 'B09G9BL5CP', 'review_id': 94},
 {'product_id': 'B09G9BL5CP', 'review_id': 95},
 {'product_id': 'B09G9BL5CP', 'review_id': 96},
 {'product_id': 'B09G9BL5CP', 'review_id': 97},
 {'product_id': 'B09G9BL5CP', 'review_id': 98},
 {'product_id': 'B09G9BL5CP', 'review_id': 99},
 {'product_id': 'B09G9BL5CP', 'review_id': 100},
 {'product_id': 'B09G9BL5CP', 'review_id': 101},
 {'product_id': 'B09G9BL5CP', 'review_id': 102},
 {'product_id': 'B09G9BL5CP', 'review_id': 103},
 {'product_id': 'B09G9BL5CP', 'review_id': 104},
 {'product_id': 'B09G9BL5CP', 'review_id': 104},
 {'product_id': 'B09G9BL5CP', 'review_id': 105},
 {'product_id': 'B09G9BL5CP', 'review_id': 106},
 {'product_id': 'B09G9BL5CP', 'review_id': 107},
 {'product_id': 'B09G9BL5CP', 'review_id': 108},
 {'product_id': 'B09G9BL5CP', 'review_id': 109},
 {'product_id': 'B09G9BL5CP', 'review_id': 110},
 {'product_id': 'B09G9BL5CP', 'review_id': 111},
 {'product_id': 'B09G9BL5CP', 'review_id': 111},
 {'product_id': 'B09G9BL5CP', 'review_id': 111},
 {'product_id': 'B09G9BL5CP', 'review_id': 111},
 {'product_id': 'B09G9BL5CP', 'review_id': 111},
 {'product_id': 'B09G9BL5CP', 'review_id': 111},
 {'product_id': 'B09G9BL5CP', 'review_id': 111},
 {'product_id': 'B09G9BL5CP', 'review_id': 111},
 {'product_id': 'B09G9BL5CP', 'review_id': 111},
 {'product_id': 'B09G9BL5CP', 'review_id': 111},
 {'product_id': 'B09G9BL5CP', 'review_id': 111},
 {'product_id': 'B09G9BL5CP', 'review_id': 111},
 {'product_id': 'B09G9BL5CP', 'review_id': 111},
 {'product_id': 'B09G9BL5CP', 'review_id': 111},
 {'product_id': 'B09G9BL5CP', 'review_id': 111},
 {'product_id': 'B09G9BL5CP', 'review_id': 111},
 {'product_id': 'B09G9BL5CP', 'review_id': 111},
 {'product_id': 'B09G9BL5CP', 'review_id': 111},
 {'product_id': 'B09G9BL5CP', 'review_id': 111},
 {'product_id': 'B09G9BL5CP', 'review_id': 111},
 {'product_id': 'B09G9BL5CP', 'review_id': 111},
 {'product_id': 'B09G9BL5CP', 'review_id': 111},
 {'product_id': 'B09G9BL5CP', 'review_id': 111},
 {'product_id': 'B09G9BL5CP', 'review_id': 111},
 {'product_id': 'B09G9BL5CP', 'review_id': 111},
 {'product_id': 'B09G9BL5CP', 'review_id': 111},
 {'product_id': 'B09G9BL5CP', 'review_id': 111},
 {'product_id': 'B09G9BL5CP', 'review_id': 111},
 {'product_id': 'B09G9BL5CP', 'review_id': 111},
 {'product_id': 'B09G9BL5CP', 'review_id': 111},
 {'product_id': 'B09G9BL5CP', 'review_id': 111},
 {'product_id': 'B09G9BL5CP', 'review_id': 111},
 {'product_id': 'B09G9BL5CP', 'review_id': 111},
 {'product_id': 'B09G9BL5CP', 'review_id': 112},
 {'product_id': 'B09G9BL5CP', 'review_id': 112},
 {'product_id': 'B09G9BL5CP', 'review_id': 113},
 {'product_id': 'B09G9BL5CP', 'review_id': 114},
 {'product_id': 'B09G9BL5CP', 'review_id': 115},
 {'product_id': 'B09G9BL5CP', 'review_id': 116},
 {'product_id': 'B09G9BL5CP', 'review_id': 117},
 {'product_id': 'B09G9BL5CP', 'review_id': 118},
 {'product_id': 'B09G9BL5CP', 'review_id': 119},
 {'product_id': 'B09G9BL5CP', 'review_id': 120},
 {'product_id': 'B09G9BL5CP', 'review_id': 120},
 {'product_id': 'B09G9BL5CP', 'review_id': 120},
 {'product_id': 'B09G9BL5CP', 'review_id': 120},
 {'product_id': 'B09G9BL5CP', 'review_id': 120},
 {'product_id': 'B09G9BL5CP', 'review_id': 120},
 {'product_id': 'B09G9BL5CP', 'review_id': 120},
 {'product_id': 'B09G9BL5CP', 'review_id': 120},
 {'product_id': 'B09G9BL5CP', 'review_id': 120},
 {'product_id': 'B09G9BL5CP', 'review_id': 120},
 {'product_id': 'B09G9BL5CP', 'review_id': 120},
 {'product_id': 'B09G9BL5CP', 'review_id': 120},
 {'product_id': 'B09G9BL5CP', 'review_id': 120},
 {'product_id': 'B09G9BL5CP', 'review_id': 120},
 {'product_id': 'B09G9BL5CP', 'review_id': 120},
 {'product_id': 'B09G9BL5CP', 'review_id': 120},
 {'product_id': 'B09G9BL5CP', 'review_id': 120},
 {'product_id': 'B09G9BL5CP', 'review_id': 120},
 {'product_id': 'B09G9BL5CP', 'review_id': 120},
 {'product_id': 'B09G9BL5CP', 'review_id': 120},
 {'product_id': 'B09G9BL5CP', 'review_id': 120},
 {'product_id': 'B09G9BL5CP', 'review_id': 120},
 {'product_id': 'B09G9BL5CP', 'review_id': 120},
 {'product_id': 'B09G9BL5CP', 'review_id': 120},
 {'product_id': 'B09G9BL5CP', 'review_id': 120},
 {'product_id': 'B09G9BL5CP', 'review_id': 120},
 {'product_id': 'B09G9BL5CP', 'review_id': 120},
 {'product_id': 'B09G9BL5CP', 'review_id': 120},
 {'product_id': 'B09G9BL5CP', 'review_id': 120},
 {'product_id': 'B09G9BL5CP', 'review_id': 121},
 {'product_id': 'B09G9BL5CP', 'review_id': 121},
 {'product_id': 'B09G9BL5CP', 'review_id': 121},
 {'product_id': 'B09G9BL5CP', 'review_id': 121},
 {'product_id': 'B09G9BL5CP', 'review_id': 121},
 {'product_id': 'B09G9BL5CP', 'review_id': 121},
 {'product_id': 'B09G9BL5CP', 'review_id': 121},
 {'product_id': 'B09G9BL5CP', 'review_id': 121},
 {'product_id': 'B09G9BL5CP', 'review_id': 122},
 {'product_id': 'B09G9BL5CP', 'review_id': 122},
 {'product_id': 'B09G9BL5CP', 'review_id': 122},
 {'product_id': 'B09G9BL5CP', 'review_id': 122},
 {'product_id': 'B09G9BL5CP', 'review_id': 122},
 {'product_id': 'B09G9BL5CP', 'review_id': 122},
 {'product_id': 'B09G9BL5CP', 'review_id': 122},
 {'product_id': 'B09G9BL5CP', 'review_id': 123},
 {'product_id': 'B09G9BL5CP', 'review_id': 123},
 {'product_id': 'B09G9BL5CP', 'review_id': 123},
 {'product_id': 'B09G9BL5CP', 'review_id': 123},
 {'product_id': 'B09G9BL5CP', 'review_id': 123},
 {'product_id': 'B09G9BL5CP', 'review_id': 123},
 {'product_id': 'B09G9BL5CP', 'review_id': 123},
 {'product_id': 'B09G9BL5CP', 'review_id': 123},
 {'product_id': 'B09G9BL5CP', 'review_id': 123},
 {'product_id': 'B09G9BL5CP', 'review_id': 123},
 {'product_id': 'B09G9BL5CP', 'review_id': 123},
 {'product_id': 'B09G9BL5CP', 'review_id': 123},
 {'product_id': 'B09G9BL5CP', 'review_id': 123},
 {'product_id': 'B09G9BL5CP', 'review_id': 123},
 {'product_id': 'B09G9BL5CP', 'review_id': 123},
 {'product_id': 'B09G9BL5CP', 'review_id': 123},
 {'product_id': 'B09G9BL5CP', 'review_id': 123},
 {'product_id': 'B09G9BL5CP', 'review_id': 123},
 {'product_id': 'B09G9BL5CP', 'review_id': 123},
 {'product_id': 'B09G9BL5CP', 'review_id': 123},
 {'product_id': 'B09G9BL5CP', 'review_id': 123},
 {'product_id': 'B09G9BL5CP', 'review_id': 123},
 {'product_id': 'B09G9BL5CP', 'review_id': 123},
 {'product_id': 'B09G9BL5CP', 'review_id': 123},

In [ ]:
chunks

['every thing is good about iphones theres nothing compared to its speed and ios but i was disappointed because theres',
 'no charger for it even though indian judiciary told them to provide still they havent made any progress regarding charger',
 'why should we spend 62k and more than that for iphones because of its brand and acessories comfort size and',
 'features right if thats not there whats point of buying an iphonethank you',
 'it look so fabulous i am android user switched to apple performance wise iphone is more better than android due',
 'to a15 bionic chip i feel pleasant while using iphone in hand i like it very much',
 'i tried to flip camera while recording but no facility is added here you have to pause first then you',
 'can flip from back to front or vice versa it means you cant continue it very awkward position iphone software',
 'should be upgraded so that we can make it go its very essential for a content creator i purchased gimbal',
 'dji om se but it could not provided that its very essential for a vlogger but i was fed up',
 'after finding the basic requirements wasnt built in these products',
 '100 genuine',
 'happy to get the iphone 13 in amazon offer',
 '5 star',
 'great product nothing to say as the name apple is own identity of this product all is well recommendation is',
 '100 just grab this product else you missed something',
 'good product',
 'nice product',
 'excellent product',
 'my honest review after going broke buying this depreciating objecti have been using android phones since the last 10 years',
 'and finally decided to switch to iphone i used to roast iphone for its prices lack of features and also',
 'things like power adapter not given in box etc but my last android phone iqoo 7 legend had lot of',
 'software related issues and battery issues after updating it to android 12 tired of bugs and software glitches in android',
 'i finally decided to buy a iphone and switch from android to ios and boy was i righti never even',
 'held an iphone in my life before because of its price but now i made a great choice even if',
 'i had to spend all my savings on itiphone 13 is so smooth that even my iqoo 7 legend with',
 '120hz feels slower than it even if iphone has only 60hz and i cant believe what im seeing all the',
 'gamesapps are so much smoother and optimised than on androidi was very sceptical about the charging speed of an iphone',
 'because in iqoo i had 66w fast charger where as for iphone i had to buy 20w separate fast charger',
 'for 1800rs but charging speed isnt disappointingdisplay quality is truly flagship level and im quite a fan of the small',
 '61 display believe it or not being able to reach the top of display with just one hand is very',
 'helpful build quality is greati would recommend not to waste extra 40k for buying 13 pro because i dont think',
 'having a extra camera telephoto lens is worth spending 40kyou can see in the 3rd image attached the quality of',
 'wide angle camera pic shot on my iphone 13 wide angle camera struggles in low light but main camera is',
 'really good captures true colours front camera is really good too truly flagshipspeakers are greatbattery life is better than my',
 'previous devicesios is very optimised in terms of battery life easy 8hrs sot on normal usagenote while playing bgmi you',
 'loose around 2 battery every 6minutes at hd extreme graphics which is also good pro max would be far better',
 'in terms of batteryfor the software yes i feel like there are few downsides even if the software is very',
 'smooth and has very less bugs it has two annoying things any game gets paused when you open control centre',
 'just to check the battery etc lock screen is annoying and also having to reach the top left corner just',
 'to see notifications is also annoying clearing all notifications is also very annoyingbut other than that a perfect 1010 purchase',
 'i was very disappointed at myself when i paid for the iphone but when i received it i was truly',
 'happy that i bought ittruly worth it',
 'nice',
 'its a perfect iphone i highly recommend this seller great price on their sale the phone is good',
 'what i like about this phone is that it is quite reasonable comparing other iphones and is very good and',
 'nice to use',
 'i bought the product little expensive within a month price dropped by rs17000',
 'though we talk a lot about high price for iphones this is worth the amount smooth touch perfect to hold',
 'in hand for the screen size of 61 it looks small overall i could have gone for pro max but',
 'more than 15l budget is way too much for me good battery backup with low battery mode always on 5',
 'hours of talktime around 2 hours of twitter and 2 hours of whatsapp usage 1 hour of songs listening 1',
 'hour of rummycandy crush games and notification of all these items the battery comes for more than 24 hours for',
 'me getting charged quickly from 20 to 100 within 2 hours perfect camera and i love that live photo option',
 'body design is awesome when i held it in my hand for the first time felt really happy about the',
 'design and the size of the iphone 13',
 'works just fine nothing special the camera is also good but during night its not what i expected it to',
 'be and you have to charge the phone twice if you use it a lot it also heat sometimes it',
 'it doesnt like but sometimes it doesnt feel very smooth i dont know if its value for money',
 'loved it',
 'theres no same day delivery phone was delivered to me in 34 days i had to purchase the phone thrice',
 'so on the third attempt i finally received the phone battery life is better than iphone xr phone is same',
 'as shown in pictures amazon refund policy is good i received both refunds within 24 hours',
 'my device is not working switched offiam not able to download invoice and warranty documenthow can i get itservice center',
 'asking the document',
 'best',
 'not worth',
 'nothing new features only model changed',
 'seals were teared but only stricker was put i dont know whether it is new or refurbished but its working',
 'this phone has well balanced hd oled sdisplay colours are accurate camera quality is very good even with 12 mp',
 'cameras selfies and portrait look good but selfies indoor required little improvement which can be done through software battery back',
 'up is great faster transfer using airdrop i am getting a 1 and half day of battery backup with normal',
 'usage overall a perfect smartphone with ios experience',
 'good not like android',
 'nan',
 'good charge',
 'actually im android user now switched to iphone user experience is good but camera quality isnt meet my expectations when',
 'taken photos on day times and little low lights youll get good quality photos night mode is worst battery is',
 'good for moderate users phone is very compact and display quality really awesome my conclusion if you looking for privacy',
 'and protect from hackers definitely iphone is safe those who are all moderate user and then buy this model',
 'very good i am happy',
 'works fine',
 'cool',
 'as it is an apple product quality is ensured and proven',
 'my phone was bent for some reason so kindly infirm check my warrenty period get me feedback',
 'fine',
 'i mainly bought it for content creation because the software optimization was good and also because i use macbook air',
 'so data transfer between iphone is quicker than the android one basically less hasslelove the photo and video qualityits also',
 'mostly for work than personal use customization is a bit hard but i also use android as primary phone so',
 'not an issue for meoverall a good purchase for me',
 'i bought this iphone 13 there was a manufacturing defect as this phone doesnthave personal hotspot and airdrop its blocked',
 'not turning on deception i cant afford this i am now in foreign my friend bought this iphone i am',
 'not in a position even to return this iphone',
 'nan',
 'i received iphone 13 timelyproduct is working greatit improved my lifestyle as wellcamera quality is awesome battery performance is pretty',
 'goodthanks to amazon for your great service',
 'facing heating issue battery performance is not that good on screen 12 hrs only as of now hanging in between',
 'which we didnt expect from apple look is fantastic small while compared to xr',
 'i finally upgraded from my trusty iphone 5s to the iphone 13 and let me tell you it feels like',
 'ive timetraveled from the past to the future the pink color is absolutely gorgeousits the perfect blend of subtle and',
 'stylish making the phone look sleek and modern ive received so many compliments on it alreadythe design is everything youd',
 'expect from apple premium wellcrafted and just a pleasure to hold coming from a 5s its almost like i was',
 'using a rotary phone before this i halfexpected siri to say welcome to the 21st centurythe display is bright and',
 'vibrant the camera is a huge leap forward and the overall performance is incredibly smooth its crazy how much has',
 'changedface id feels like magic and the battery life is a dream compared to my old 5s which needed a',
 'charger practically glued to itif youre thinking about upgrading especially if youre coming from a much older model like i',
 'was dont hesitate this iphone 13 in pink is a stunner and well worth the leap',
 'i really wanted to get an iphone and it is my first iphone but i loved it the sound quality',
 'is great and it charges fast the phone is a bit heavy but it looks classy the display also works',
 'well and the camera is the best',
 'things i liked1 solid build quality and very polished software compared to samsungs one ui2 camerarear rear camera is pretty',
 'decent with good color accuracy in all lighting conditions videos are steady and smooth3 mic speakers mic is exceptionally well',
 'isolates all background sounds in noisy situations speakers are crisp with good bass4 performance this is where the phone shines',
 'you can throw any app available on the app store and it will run it without breaking a sweat5 face',
 'id works like charm its the best biometric phone lock out there undoubtedlythings i wish were better1 battery life would',
 'have been better i get up to 430 5 hours sot with mixed usage high brightness 1 hour calls 23',
 'hour social media and 2 hour media playbackmusic2 charges slow compared to my earlier samsung takes almost 12 hours from',
 '20 to 803 front camera is average it fails to get correct skin tones and lighting i keep it on',
 'default and still it produces over saturated photos4 dialer phone app sucks i am someone who makes up to 200',
 'calls a day due to nature of my scm work dialer on samsung is far better for unknown call you',
 'can add a note to the number in samsung and it reflect when the person call you again without having',
 'to save unnecessary contacts number pad does not detect contact unless complete number is typed',
 'each and every thinglove this product',
 'i liked the way it was fast',
 'ios 175 current version updated from 166thw worst thing as a ios user for me that the fear of update',
 'i heared some updates get display issues battery drain issues god sake i doesnt had any issues from ios updates',
 'but till i care device was great super handy for me little feeling of weight display the 60hz refresh rate',
 'didnt felt badly form me cause i am used such kind of device before the brightness range is so comfortable',
 'the 2160p60 hdr videos in youtube give blissful experiancebattery and charging the charging time i took 1hour to charge from',
 '20 to 91 using apple 20w original adapter and cable without any interruptionno electricity break or disconnection calls etc battery',
 'backup i am mostly maintain battery in btw 20 80 so i think this may get one day backup for',
 'me average 5h screen on timethe one day backup is just a advertisemnt advertisement label usaully we use actually a',
 'day like eventspartyouting we use camera editing app social media app more than usual use that day i didnt get',
 'a satisfied backup little temperature warming while charging no heating issue battery health after 6 month 98battery cycle count 194',
 'after 6 monthperfomance good perfomance for video editing photography social media i am not a gamer camera even though i',
 'felt some lag or stuck screens in some third party applications the cinematic mode is mind blowing i missed 13',
 'pro or higher varients for zooming in this mode actually i really miss pro variant for the tele lens and',
 'camera features while i using this cost is wall for me the photos are nice and feature like exposure adjust',
 'and filter was good and quality photos and the 5x zoomed photos is not good for meit reduced the pixel',
 'quality the video and optical image stabilisation was mind blowing i mostly explore on videos it was soo good no',
 'words other than thatand the biggest fear for me now is ios updatei turned off the auto update at first',
 'place i heared about display issuesheating issues and bugs in the ios updates for 13 and 14 seriesso for expencive',
 'and established brand like apple does not fair this is the only ve i have to say as a reminder',
 'also i heared without ios update display issues are happened buy the way it is a hardware issue one of',
 'the display provider companys batch may show the issues but we customers cannot identify which company provides the hardawarei will',
 'attach my battery analytics data screnshot photo here so you can better understand how the battery is good the ordering',
 'experience in the greate indian sale was worst i planned to buy this for 45999 in oct7 greate indian sale',
 'offer but i got canceled then i bought for 48999 that was disppointed as a whole i didnt recommend base',
 'models i felt i must have buy pro variant but for person who need ios in affordable price i recommend',
 '13 is better than 14',
 'im using it from almost 2 months there no issue im facing as such now camera quality is great and',
 'best part is its display gives you premium experience u can go for it',
 'picture quality is fine but hanging issue',
 'writing this review after using the phone for 5 monthspros camera clicks amazing pictures video recording is the best ive',
 'seen in a phone so far compared to my previous phones stable videos with no shaking battery life is good',
 'lasts an entire day with medium use i dont game on the phone charging is as quick as it is',
 'with phones that use usb c display is soo good so bright built is solid dropped phone a couple of',
 'times once with the cover and once without and not even a scratch listening to music and watching videos is',
 'a hot cos of how good the speakers r crystal clear with the right amount of bass and treblecons phone',
 'is a tad heavy and using it for hrs on a stretch can result in pain in the wrist or',
 'fingersgot the phone in diwali sale on discount so bang for buck if u ask me',
 'best phone',
 'nice one',
 'finally switched from android in hand feel is super amazing they are still susceptible to hacking among other types of',
 'security threats photos comes out ver good screen quality is wow i mean watching experience is super satisfying',
 'the new i phone 13 purchased by me is developing overheating while using charging may be duplicate product being supplied',
 'online my request to amazon is to change the phone',
 'the iphone 13 is without a doubt a gamechanger as an avid apple user i recently upgraded to this incredible',
 'device and it has exceeded my already high expectations in every way heres why i am thoroughly impressed with the',
 'iphone 13performance the a15 bionic chip is a powerhouse it makes everything i do on my phone feel lightningfast and',
 'seamless whether im gaming streaming or multitasking the iphone 13 handles it all effortlesslydisplay the super retina xdr display is',
 'a work of art the colors are vivid the brightness is exceptional and the contrast is stunning whether im watching',
 'movies browsing the web or scrolling through social media the visual experience is second to nonecamera the camera system on',
 'the iphone 13 is nothing short of amazing it captures photos and videos with outstanding clarity and detail the night',
 'mode has been a gamechanger for lowlight photography and the cinematic mode for videos adds a whole new dimension to',
 'my creative endeavorsbattery life apple has improved battery life on the iphone 13 and it shows i can go through',
 'an entire day of heavy usage without needing to reach for a charger the battery management features are also impressive',
 'ensuring i get the most out of every chargeios the iphone 13 runs on ios and the user experience is',
 'unmatched the interface is intuitive and the app store offers a vast ecosystem of apps that enhance the devices capabilitiesdesign',
 'the iphone 13 boasts a sleek and premium design its durable and feels great in hand the ceramic shield front',
 'cover offers extra protection which is a welcome addition5g capability the iphone 13 is 5gready which means i can experience',
 'lightningfast data speeds and low latency making it futureproof and ready for the latest advancements in mobile technologyprivacy and security',
 'apples commitment to user privacy and security is commendable with features like face id and enhanced data protection i feel',
 'confident that my personal information is in safe handsin summary the iphone 13 is a stunning upgrade delivering on apples',
 'legacy of innovation and excellence it offers exceptional performance a breathtaking display a camera system that redefines mobile photography and',
 'videography and a design that exudes luxury this device is a testament to apples commitment to pushing the boundaries of',
 'what a smartphone can be if youre looking for the best in the business the iphone 13 is it i',
 'wholeheartedly recommend it to anyone seeking a toptier mobile experience its worth every penny and more',
 'usb cable was defective it was not charging',
 'good',
 'its a my dream phone always working proper and processor is strong and mainly camera is always better than other',
 'phone but but i am unhappy withh main heating issue please solve the heating issue at the charging time phone',
 'is always produced more heating',
 'excellent features',
 'when talking about phone apple is always costly and there are always ve and ve for everythingi have been using',
 'android for 10 year and now i moved to applethere are lot of applications and few features which i am',
 'missing while moved to apple but what really impressed me is the power of its processor and capabilities1 when android',
 'phone comes with 6 8 12 gb ram the speed or performance is poor at the same time with 4',
 'gb ram in iphone was really powerful and mindblowing2 when android storage are full the phone will response very slow',
 'but apple still surprised me with the performance3 the video quality of anroid phone gives from 48 mp is delivered',
 'from apples 12 mp camera which is mesmerizing and absolutely brilliant the battery back up is okay but could have',
 'improved as i am not using for gaming it is okay to me as apple started production in india the',
 'price could have reduced',
 'good product delivered on time',
 'nice',
 'very happy with the purchase product is genuine but this is my third time when exchang not worked amazon mentioned',
 'the value of old phone but delivery guy 2 times denied accepting the exchange with 2 diff phones in 2',
 'instances very bad experience with exchange not trustworthy in this',
 'value for money',
 'no 1 mobile phone',
 'although iphone handling is quite different in compare to android phone but this number is comparatively easier than others',
 'best',
 'all over good price is good less than other sources but its have heating issues while charging device i know',
 'apple devices have heated while charging but its too hot than other devices',

In [ ]:
model = SentenceTransformer('all-MiniLM-L6-v2')
embeddings = model.encode(chunks,convert_to_numpy= True)
embeddings

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:112: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

README.md:   0%|          | 0.00/10.5k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/612 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/90.9M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

tokenizer_config.json:   0%|          | 0.00/350 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

array([[-0.02696455,  0.02999497,  0.07132509, ..., -0.05796148,
         0.05524072,  0.13675663],
       [-0.08033787,  0.09218963, -0.05183384, ..., -0.03947391,
        -0.01438533,  0.04200704],
       [ 0.00769377,  0.08479298,  0.05187638, ..., -0.12554216,
        -0.0607058 ,  0.06046386],
       ...,
       [-0.13236727,  0.08389042,  0.06909958, ...,  0.02577613,
        -0.01951098,  0.10076311],
       [ 0.01481783,  0.06807026,  0.01756978, ..., -0.01758698,
         0.00928347,  0.04424087],
       [-0.00946623,  0.06474222,  0.01569523, ...,  0.06423365,
        -0.10020681, -0.01162443]], dtype=float32)

In [ ]:
dim = embeddings.shape[1]

In [ ]:
index = faiss.IndexFlatL2(dim)
index.add(embeddings)

In [ ]:
def recommend_products(user_query,top_k = 3):
  query_vec = model.encode([user_query],convert_to_numpy=True)
  distances,indices = index.search(query_vec,top_k)

  retrieved_chunks = [chunks[i] for i in indices[0]]
  retrieved_metadata = [metadata[i] for i in indices[0]]

  context = "\n".join([f"product{m['product_id']}:{txt}" for txt,m in zip(retrieved_chunks,retrieved_metadata)])

  completion = client.chat.completions.create(
    model="llama-3.1-8b-instant",
      messages = [
          {"role":"system","content":"You are helpfull product recomendation assitant"},
          {"role":"user","content":f"Based on the following customer reviews:\n{context}\n\n suggest the best product"}
      ],
      temperature = 0.2,
      max_tokens = 200
  )


  return completion.choices[0].message.content,retrieved_metadata

In [ ]:
recommend_products('I need a mobile phone with good bettery and camera')

('Based on the customer reviews, it seems that there are mixed opinions about the product. However, the majority of the reviews are negative, specifically mentioning the camera performance.\n\nOut of the 3 reviews, 2 of them mention that the camera is "pathetic" and "not good", while the third review is extremely positive, stating that the camera is "amazing".\n\nGiven the conflicting opinions, I would suggest that the product may not be the best choice for someone looking for a good camera phone. However, if you\'re looking for a phone with a great camera, you may want to consider other options, such as the Samsung S23 Plus, which was mentioned in one of the reviews.\n\nIf you could provide more information about what you\'re looking for in a phone, I may be able to suggest a more specific product recommendation.',
 [{'product_id': 'B0BDK8LKPJ', 'review_id': 1432},
  {'product_id': 'B0BDK8LKPJ', 'review_id': 1432},
  {'product_id': 'B0BDK8LKPJ', 'review_id': 1488}])

In [ ]:
test_queries = [('long bettery life','P101'),
                ('fast performance','P103')]

test_queries

[('long bettery life', 'P101'), ('fast performance', 'P103')]

In [ ]:
correct = 0
for query, expected_product in test_queries:
  response,meta = recommend_products(query,top_k=1)
  if meta[0]["product_id"] == expected_product:
    correct += 1

accuracy = correct/len(test_queries)
accuracy

0.0

In [ ]:
!pip install gradio

Requirement already satisfied: gradio in /usr/local/lib/python3.12/dist-packages (5.50.0)
Requirement already satisfied: aiofiles<25.0,>=22.0 in /usr/local/lib/python3.12/dist-packages (from gradio) (24.1.0)
Requirement already satisfied: anyio<5.0,>=3.0 in /usr/local/lib/python3.12/dist-packages (from gradio) (4.13.0)
Requirement already satisfied: brotli>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from gradio) (1.2.0)
Requirement already satisfied: fastapi<1.0,>=0.115.2 in /usr/local/lib/python3.12/dist-packages (from gradio) (0.136.3)
Requirement already satisfied: ffmpy in /usr/local/lib/python3.12/dist-packages (from gradio) (1.0.0)
Requirement already satisfied: gradio-client==1.14.0 in /usr/local/lib/python3.12/dist-packages (from gradio) (1.14.0)
Requirement already satisfied: groovy~=0.1 in /usr/local/lib/python3.12/dist-packages (from gradio) (0.1.2)
Requirement already satisfied: httpx<1.0,>=0.24.1 in /usr/local/lib/python3.12/dist-packages (from gradio) (0.28.1)
Requirement already satisfied: huggingface-hub<2.0,>=0.33.5 in /usr/local/lib/python3.12/dist-packages (from gradio) (1.17.0)
Requirement already satisfied: jinja2<4.0 in /usr/local/lib/python3.12/dist-packages (from gradio) (3.1.6)
Requirement already satisfied: markupsafe<4.0,>=2.0 in /usr/local/lib/python3.12/dist-packages (from gradio) (3.0.3)
Requirement already satisfied: numpy<3.0,>=1.0 in /usr/local/lib/python3.12/dist-packages (from gradio) (2.0.2)
Requirement already satisfied: orjson~=3.0 in /usr/local/lib/python3.12/dist-packages (from gradio) (3.11.9)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from gradio) (26.2)
Requirement already satisfied: pandas<3.0,>=1.0 in /usr/local/lib/python3.12/dist-packages (from gradio) (2.2.2)
Requirement already satisfied: pillow<12.0,>=8.0 in /usr/local/lib/python3.12/dist-packages (from gradio) (11.3.0)
Requirement already satisfied: pydantic<=2.12.3,>=2.0 in /usr/local/lib/python3.12/dist-packages (from gradio) (2.12.3)
Requirement already satisfied: pydub in /usr/local/lib/python3.12/dist-packages (from gradio) (0.25.1)
Requirement already satisfied: python-multipart>=0.0.18 in /usr/local/lib/python3.12/dist-packages (from gradio) (0.0.32)
Requirement already satisfied: pyyaml<7.0,>=5.0 in /usr/local/lib/python3.12/dist-packages (from gradio) (6.0.3)
Requirement already satisfied: ruff>=0.9.3 in /usr/local/lib/python3.12/dist-packages (from gradio) (0.15.16)
Requirement already satisfied: safehttpx<0.2.0,>=0.1.6 in /usr/local/lib/python3.12/dist-packages (from gradio) (0.1.7)
Requirement already satisfied: semantic-version~=2.0 in /usr/local/lib/python3.12/dist-packages (from gradio) (2.10.0)
Requirement already satisfied: starlette<1.0,>=0.40.0 in /usr/local/lib/python3.12/dist-packages (from gradio) (0.52.1)
Requirement already satisfied: tomlkit<0.14.0,>=0.12.0 in /usr/local/lib/python3.12/dist-packages (from gradio) (0.13.3)
Requirement already satisfied: typer<1.0,>=0.12 in /usr/local/lib/python3.12/dist-packages (from gradio) (0.25.1)
Requirement already satisfied: typing-extensions~=4.0 in /usr/local/lib/python3.12/dist-packages (from gradio) (4.15.0)
Requirement already satisfied: uvicorn>=0.14.0 in /usr/local/lib/python3.12/dist-packages (from gradio) (0.49.0)
Requirement already satisfied: fsspec in /usr/local/lib/python3.12/dist-packages (from gradio-client==1.14.0->gradio) (2025.3.0)
Requirement already satisfied: websockets<16.0,>=13.0 in /usr/local/lib/python3.12/dist-packages (from gradio-client==1.14.0->gradio) (15.0.1)
Requirement already satisfied: idna>=2.8 in /usr/local/lib/python3.12/dist-packages (from anyio<5.0,>=3.0->gradio) (3.18)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from fastapi<1.0,>=0.115.2->gradio) (0.4.2)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from fastapi<1.0,>=0.115.2->gradio) (0.0.4)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1.0,>=0.24.1->gradio) (2026.5.20)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1.0,>=0.24.1->gradio) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1.0,>=0.24.1->gradio) (0.16.0)
Requirement already satisfied: click>=8.4.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=0.33.5->gradio) (8.4.1)
Requirement already satisfied: filelock>=3.10.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=0.33.5->gradio) (3.29.1)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=0.33.5->gradio) (1.5.0)
Requirement already satisfied: tqdm>=4.42.1 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=0.33.5->gradio) (4.67.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas<3.0,>=1.0->gradio) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas<3.0,>=1.0->gradio) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas<3.0,>=1.0->gradio) (2026.2)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<=2.12.3,>=2.0->gradio) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic<=2.12.3,>=2.0->gradio) (2.41.4)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer<1.0,>=0.12->gradio) (1.5.4)
Requirement already satisfied: rich>=13.8.0 in /usr/local/lib/python3.12/dist-packages (from typer<1.0,>=0.12->gradio) (13.9.4)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas<3.0,>=1.0->gradio) (1.17.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=13.8.0->typer<1.0,>=0.12->gradio) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=13.8.0->typer<1.0,>=0.12->gradio) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=13.8.0->typer<1.0,>=0.12->gradio) (0.1.2)

In [ ]:
import gradio as gr
iface = gr.Interface(fn = recommend_products,
                      inputs = gr.Textbox(lines=2,placeholder="Ask Something...."),
                      outputs = "text",
                      title = "Recommendation Chat bot")
iface.launch()

It looks like you are running Gradio on a hosted Jupyter notebook, which requires `share=True`. Automatically setting `share=True` (you can turn this off by setting `share=False` in `launch()` explicitly).

Colab notebook detected. To show errors in colab notebook, set debug=True in launch()
* Running on public URL: https://919d21bf4db2771a43.gradio.live

This share link expires in 1 week. For free permanent hosting and GPU upgrades, run `gradio deploy` from the terminal in the working directory to deploy to Hugging Face Spaces (https://huggingface.co/spaces)